name: Test

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm i

      - name: Build
        run: pnpm run build
        env:
          NODE_OPTIONS: --max-old-space-size=8048

      - name: Typecheck
        run: pnpm typecheck && pnpm test:attw

      - name: Test
        run: pnpm run test
